/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sos-active`; params?: Router.UnknownInputParams; } | { pathname: `/../landing/vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../landing/src/main`; params?: Router.UnknownInputParams; } | { pathname: `/../landing/src/App`; params?: Router.UnknownInputParams; } | { pathname: `/../responder/vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../responder/src/main`; params?: Router.UnknownInputParams; } | { pathname: `/../responder/src/App`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/sos-active`; params?: Router.UnknownOutputParams; } | { pathname: `/../landing/vite.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../landing/src/main`; params?: Router.UnknownOutputParams; } | { pathname: `/../landing/src/App`; params?: Router.UnknownOutputParams; } | { pathname: `/../responder/vite.config`; params?: Router.UnknownOutputParams; } | { pathname: `/../responder/src/main`; params?: Router.UnknownOutputParams; } | { pathname: `/../responder/src/App`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/contacts` | `/contacts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/sos-active${`?${string}` | `#${string}` | ''}` | `/../landing/vite.config${`?${string}` | `#${string}` | ''}` | `/../landing/src/main${`?${string}` | `#${string}` | ''}` | `/../landing/src/App${`?${string}` | `#${string}` | ''}` | `/../responder/vite.config${`?${string}` | `#${string}` | ''}` | `/../responder/src/main${`?${string}` | `#${string}` | ''}` | `/../responder/src/App${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/contacts${`?${string}` | `#${string}` | ''}` | `/contacts${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sos-active`; params?: Router.UnknownInputParams; } | { pathname: `/../landing/vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../landing/src/main`; params?: Router.UnknownInputParams; } | { pathname: `/../landing/src/App`; params?: Router.UnknownInputParams; } | { pathname: `/../responder/vite.config`; params?: Router.UnknownInputParams; } | { pathname: `/../responder/src/main`; params?: Router.UnknownInputParams; } | { pathname: `/../responder/src/App`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
